version: "3.5"

services:
  gve_devnet_meraki_seamless_sea_ssid:
    image: ghcr.io/gve-sw/gve_devnet_meraki_seamless_sea_ssid:latest
    container_name: gve_devnet_meraki_seamless_sea_ssid
    environment:
      - APP_NAME= ${APP_NAME}
      - CSV_FILE = ${CSV_FILE}
      - MERAKI_BASE_URL = ${MERAKI_BASE_URL}
      - MERAKI_API_KEY = ${MERAKI_API_KEY}
      - UVICORN_LOG_LEVEL = ${UVICORN_LOG_LEVEL}
#    volumes:
#      - config.yaml:/app/config.yaml
    restart: "always"
